name: mysql
default: true
update_strategy: minor
track_latest: true
description: MySQL database
family: mysql
default_version: "8.4"
versions:
  - tag: "9.7"
    label: "9.7 LTS"
    image: docker.io/library/mysql:9.7
    host_port: 3397
  - tag: "8.4"
    label: "8.4 LTS (default)"
    image: docker.io/library/mysql:8.4
    canonical: true
    host_port: 3306
  - tag: "5.7"
    label: "5.7"
    image: docker.io/library/mysql:5.7
    host_port: 3357
ports:
  - "{{host_port}}:3306"
data_dir: /var/lib/mysql
environment:
  MYSQL_ROOT_PASSWORD: lerd
  MYSQL_DATABASE: lerd
env_vars:
  - DB_CONNECTION=mysql
  - DB_HOST=lerd-{{name}}
  - DB_PORT=3306
  - DB_DATABASE=lerd
  - DB_USERNAME=root
  - DB_PASSWORD=lerd
connection_url: mysql://root:lerd@127.0.0.1:{{host_port}}/lerd
