name: soketi
description: Soketi realtime WebSocket server (Pusher-compatible)
image: quay.io/soketi/soketi:1.6-16-alpine
ports:
  - "6001:6001"
environment:
  SOKETI_DEFAULT_APP_ID: lerd
  SOKETI_DEFAULT_APP_KEY: lerd
  SOKETI_DEFAULT_APP_SECRET: lerd
env_vars:
  - BROADCAST_CONNECTION=pusher
  - PUSHER_APP_ID=lerd
  - PUSHER_APP_KEY=lerd
  - PUSHER_APP_SECRET=lerd
  - PUSHER_HOST=lerd-soketi
  - PUSHER_PORT=6001
  - PUSHER_SCHEME=http
  - PUSHER_APP_CLUSTER=mt1
  - VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
  - VITE_PUSHER_HOST=localhost
  - VITE_PUSHER_PORT="${PUSHER_PORT}"
  - VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
  - VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
env_detect:
  composer: pusher/pusher-php-server
connection_url: http://127.0.0.1:6001
