package cli

import (
	"fmt"
	"strings"
)

// These builders are kept in a non-build-tagged file so they can be unit-
// tested on any platform. worker_darwin.go calls into them.

// buildDarwinExecWorkerService renders the systemd-style service unit that
// `services.Mgr.WriteServiceUnit` (macOS launchd backend) will translate
// into a launchd plist. ExecStart points at a pre-written guard script
// because parseServiceUnit in the launchd translator uses strings.Fields
// on ExecStart, so an inline multi-line script would not survive the
// split. scriptPath must contain no whitespace.
func buildDarwinExecWorkerService(scriptPath, restart string) string {
	return fmt.Sprintf(`[Unit]
Description=Lerd Worker (exec mode)

[Service]
Type=simple
Restart=%s
ExecStart=/bin/sh %s

[Install]
WantedBy=default.target
`, restart, scriptPath)
}

// buildDarwinExecWorkerGuardScript returns the shell script body written
// to disk for each worker in exec mode. It wraps buildWorkerGuard with a
// shebang so launchd's /bin/sh invocation has a self-contained executable.
//
// podmanBin / container / sitePath / workerCmd are threaded through so the
// guard can reach into the container and clean up an orphan worker that
// survived a host-side podman-exec death (suspend/wake), scoped to the
// site's working directory so multi-site shared FPM containers stay
// isolated. runCmd is the full `podman exec ...` invocation that is
// finally `exec`'d.
func buildDarwinExecWorkerGuardScript(pidFile, podmanBin, container, sitePath, workerCmd, runCmd string) string {
	return "#!/bin/sh\n" + buildWorkerGuard(pidFile, podmanBin, container, sitePath, workerCmd, runCmd)
}

// buildDarwinHostWorkerService renders the systemd-style service unit
// for a host-mode worker (vite + future Node tooling). Mirrors
// buildDarwinExecWorkerService but the ExecStart points at the host
// guard script — there is no podman exec in this path. The launchd
// translator (parseServiceUnit) reads ExecStart and Restart.
func buildDarwinHostWorkerService(scriptPath, restart string) string {
	return fmt.Sprintf(`[Unit]
Description=Lerd Worker (host mode)

[Service]
Type=simple
Restart=%s
ExecStart=/bin/sh %s

[Install]
WantedBy=default.target
`, restart, scriptPath)
}

// lerdBinDir is prepended to PATH so the php/composer/laravel/node
// shims are reachable from npm-spawned subprocesses (e.g. Inertia's
// wayfinder Vite plugin shelling out to `php artisan`) — issue #375.
func buildDarwinHostWorkerGuardScript(fnmBin, lerdBinDir, nodeVersion, sitePath, command string) string {
	escapedPath := strings.ReplaceAll(sitePath, "'", `'"'"'`)
	escapedCmd := strings.ReplaceAll(command, "'", `'"'"'`)
	escapedBin := strings.ReplaceAll(lerdBinDir, `"`, `\"`)
	// Non-Node host-proxy commands (Python, Ruby, Go, …) run directly; only
	// Node projects are routed through fnm to pin the Node version.
	execLine := fmt.Sprintf("exec /bin/sh -c '%s'", escapedCmd)
	if nodeVersion != "" {
		execLine = fmt.Sprintf("exec '%s' exec --using=%s -- /bin/sh -c '%s'", fnmBin, nodeVersion, escapedCmd)
	}
	return fmt.Sprintf(`#!/bin/sh
# Generated by lerd. Host-mode worker guard.
export PATH="%s:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
cd '%s' || exit 1
%s
`, escapedBin, escapedPath, execLine)
}

// buildDarwinContainerWorkerUnit renders the quadlet `[Container]` body
// used by macOS's current (container) worker runtime mode. One container
// per worker, spawned from the FPM image or the site's custom image.
// Kept as an explicit builder to match buildDarwinExecWorkerService so
// tests cover both branches uniformly.
func buildDarwinContainerWorkerUnit(
	unitName, phpVersion, sitePath, homeDir, phpConfFile, phpUserIniFile, command, restart string,
	customContainer bool,
) string {
	if customContainer {
		// Custom container sites reuse their own image; the caller has
		// already determined it via podman.CustomImageName(siteName), so
		// here we only build the quadlet template and leave the image
		// name to be filled in by the caller. To keep this builder pure
		// we emit a placeholder that the caller substitutes.
		return fmt.Sprintf(`[Container]
Image=<custom-image>
ContainerName=%s
Network=lerd
Volume=%s/.local/share/lerd/hosts:/etc/hosts:ro
Volume=%s:%s:rw
PodmanArgs=--security-opt=label=disable
WorkingDir=%s
Exec=%s

[Service]
Restart=%s
`,
			unitName,
			homeDir,
			sitePath, sitePath,
			sitePath,
			command,
			restart,
		)
	}
	versionShort := strings.ReplaceAll(phpVersion, ".", "")
	image := "lerd-php" + versionShort + "-fpm:local"
	return fmt.Sprintf(`[Container]
Image=%s
ContainerName=%s
Network=lerd
Volume=%s/.local/share/lerd/hosts:/etc/hosts:ro
Volume=%s:%s:rw
Volume=%s:/usr/local/etc/php/conf.d/99-xdebug.ini:ro
Volume=%s:/usr/local/etc/php/conf.d/98-lerd-user.ini:ro
PodmanArgs=--security-opt=label=disable
WorkingDir=%s
Exec=%s

[Service]
Restart=%s
`,
		image,
		unitName,
		homeDir,
		sitePath, sitePath,
		phpConfFile,
		phpUserIniFile,
		sitePath,
		command,
		restart,
	)
}
